### ISSUE TITLE
The ./devsus.sh script bailled out with an error. so i did...

### ISSUE THREAD

**Issue by forsland** [dimkr/devsus#18]
The devsus.sh script didn't work for me. And somehow found out the downloads were at  https://github.com/dimkr/devsus/releases/download/beowulf-cb46f61/  I fiddles with the script and got the two img files built.

I commented out the branch and commit variables and wrote beowulf-cb46f61 ($branch-$commit).

Is it safe to use the devuan-beowulf-c201-libre-2GB.img image

regards Forsland
[devsus.sh.zip](https://github.com/dimkr/devsus/files/3995238/devsus.sh.zip)

**Comment by dimkr** [comment]
`git clone http://github.com/dimkr/devsus; cd devsus; ./devsus.sh` should work. You cloned the `beowulf` development branch instead of `master`.
