### ISSUE TITLE
Devsus script requires sudo 

### ISSUE THREAD

**Issue by SolidEva** [dimkr/devsus#8]
Maybe this is obvious, but the -2GB and -16GB images are only successfully created when `sudo ./devsus.sh` is used instead of `./devsus.sh`. 
Many of the commands in create_image() require it.
Otherwise the script just spits out a "devuan-jessie-c201-libre-2GB.img" that is completely empty and has a broken gpt table. 

PS. I'm curious what issue you found "Replaced dwc2 with the one from Chrome OS" fixed. 

Thanks!

**Comment by dimkr** [comment]
> PS. I'm curious what issue you found "Replaced dwc2 with the one from Chrome OS" fixed.

The kernel freezes when you use a USB WiFi dongle because of bugs in dwc2. The Chrome OS kernel has Rockchip-provided fixes that were not merged to mainline. I'm still not sure if all issues are gone, because these days, university allows me to work on Devsus for several hours, once a month or so.

**Comment by SolidEva** [comment]
> The kernel freezes when you use a USB WiFi dongle because of bugs in dwc2.

At what point in the boot process were you experiencing this?

**Comment by ghost** [comment]
Sometimes the boot process hangs simply because the kernel hangs. If I plug it in and run `wpa_supplicant`, it's a matter of seconds until this happens.
